- lib/App/index.js
- lib/Modules/NpmCommands.js
- package-lock.json
- package.json
This is a reworked version of https://github.com/athombv/node-athom-cli/pull/152, which includes support for pruning dev dependencies.
The previously used package gitignore-parser actually showed very different behavior from actual .gitignore files. See issue https://github.com/athombv/node-athom-cli/issues/151 for details on this.
I had to use a bit of a trick to include some default ignore rules, for dotfiles, `env.json`, etc.
Because of this, I also changed the output of `_getPrunePaths` a little.
Pro tip:
Since this implementation works recursively like .gitignore does, npm packages like `homey-meshdriver` could even include their own .homeyignore file, which makes sure that some unneeded things do not included in store apps.
> Use ignore-walk package to implement .homeyignore

- lib/App/index.js
Fixes buffer constructor deprecation warning when running `homey`
```
(node:1536) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```
> fix: deprecated buffer constructor usage

- lib/App/index.js
Hello Athom team 👋 
`homey app validate` command doesn't return correct exit code in case of validation errors.
It's always `0`:
```
➜  com.gree git:(master) ✗ ../node-homey/bin/homey.js app validate --level publish  
✓ Pre-processing app...
✓ Validating app...
✖ Homey App did not validate against level `publish`:
[
{
"keyword": "required",
"dataPath": "",
"schemaPath": "#/required",
"params": {
"missingProperty": "images"
},
"message": "should have required property 'images'"
}
]
➜  com.gree git:(master) ✗ echo $?
0
```
It would be nice to get an error exit code in case of validation was not passed.
I've prepared this PoC PR. Please let me know if you would like to have it in a different way. I'll prepare changes. Or feel free to rework it 🚀
> [PoC] Add exit code for homey app validate command

- lib/AppPluginZigbee/index.js
In a future update homey-zigbeedriver will list zigbee-clusters as peer dependency instead of regular dependency. This commit ensures that the peer dependency is always installed (hence a compatible version).
> feat: check for homey-zigbeedriver peer dependency zigbee-clusters

- lib/App/index.js
Additionally, bumps lodash from 4.17.15 to 4.17.19.
> feat: check for homey-zigbeedriver peer dependency zigbee-clusters #minor

- lib/App/index.js
writes `app.json` twice if homeycompose is enabled, once to `/.homeycompose/app.json` and once to `/app.json`
> feat: create .homeycompose/app.json

- assets/templates/app/app.js
- assets/templates/app/drivers/device.js
- assets/templates/app/drivers/driver.js
- lib/App/index.js
This PR adds all overridable methods to the `app.js`, `driver.js` and `device.js` templates with some comments that explain the purpose of the methods.
I also updated the default `app.json` to set the SDK version to `3`.
I will follow up with a PR that enables homey-compose by default.
> feat: update templates for sdk v3

- lib/AppPluginCompose/index.js
This prevents `replaceSpecialPropertiesRecursive` from mutating the `"hint"` values for all settings at the same time.
See https://bugs.athom.com/youtrack/issue/SUP-2319
More context:
A settings template can be used with homey compose, this template might look like this:
**reportThreshold.json**
```json
{
"value": 200,
"label": {
"en": "Report threshold",
"nl": "Rapportage drempel"
},
"hint": {
"en": "This parameter ({{zwaveParameterIndex}}) determines the minimum change in value before reporting changes to Homey.",
"nl": "Deze parameter ({{zwaveParameterIndex}}) bepaalt de minimum verandering van de meetwaarde voordat deze naar Homey wordt gestuurd."
},
"zwave": {
"index": 40,
"size": 2
},
"attr": {
"min": 0,
"max": 32767
},
"type": "number"
}
```
Spreading we combine templates shallowly …
> fix: deep clone settings templates to prevent mutation

- lib/App/index.js
Since we set the `sdk` property to `3` by default we probably should also set the compatibility to `>=5.0.0` otherwise the default app won't work.
> fix: sdk v3 5.0.0 compatibility

- lib/App/index.js
- lib/AppPluginCompose/index.js
This adds a note to `app.json` when it is generated by homey compose to warn developers to not edit the "normal" `app.json`.
> fix: add note to compose app.json manifest

- lib/App/index.js
This PR removes the `process.exit()` on a disconnect from ManagerDevkit.
Losing the connection is still an issue but now it will at least try to reconnect.
What this looks like in practice:
> fix: allow reconnect

- lib/App/index.js
From https://athomcommunity.slack.com/archives/C04SUGZ9E/p1604955941191500
I believe args are optional so we should check whether they are present before attempting to loop over them.
I also noticed that the `removeThisFlow` was part of the loop over `args` but I think it's fine if we do that only once after the loop.
> fix: undefined card args

- lib/App.js
Same issue and fix as for discovery and flow.
Not super happy with it as is but since we may be adding additional steps to preprocess (🎉 ) this seemed like the best fix.
> fix: don't check App.getManifest in preprocess

- lib/HomeyCompose.js
This makes the behaviour of `$filter` "Driver Flow Compose" option more similar to the `filter` option of "Flow card device arguments". This way the documentation be simpler because I can choose to only explain the object syntax plus the `|` and `,` characters.
Alternatively I update the documentation to only explain the URL search params syntax for `filter` and we keep not supporting the object style.
> feat: compose allow filter override to be an object

- lib/HomeyCompose.js
Reverts athombv/node-homey#161
This breaks `titleFormatted` validation because it always tries to parse the filter as a querystring to figure out which arguments are device arguments. https://github.com/athombv/node-homey-lib/pull/275
I'm not 100% confident but I think the "missing argument" validation is also ran on Homey this is a backwards incompatible change. If we want to still support the "object-style" for `$filter` we can go from object to string instead of string to object.
> Revert "feat: compose allow filter override to be an object"

- lib/App.js
Fixes: https://github.com/athombv/homey-apps-sdk-issues/issues/198
Makes `.homeycompose/app.json` optional in the `homey app version` command (which is also part of `homey app publish`). We fallback to the "regular" `app.json` if it doesn't exist.
I also added a warning when `.homeycompose/app.json` is missing, I'm not sure we should warn but I thought I'd suggest it.
> fix: version app json

- lib/HomeyCompose.js
This fixes the issue that https://github.com/athombv/node-homey/pull/161 attempted to fix.
Filters can be objects with arrays, these are all correctly encoded by `url.URLSearchParams()`. Homey uses `querystring.parse` to read the values from the filter which works with the output of the `URLSearchParams`.
> fix: support filter object

- lib/App.js
Ensures the generated Flow passes validation.
Tried to update the inquirer version to one that supports `"type": "number"` but ran into issues with the default values.
> fix: ensure Flow number argument options are numbers

- lib/HomeyCompose.js
Fixes: https://github.com/athombv/homey-apps-sdk-issues/issues/216
Small regression from the eslint fix changes. Updated the code to check `value !== null` in addition to `typeof value === 'object'` everywhere.
> fix: check object is not null

- lib/HomeyCompose.js
Fixes https://github.com/athombv/homey-apps-sdk-issues/issues/218
The check used to be
https://github.com/athombv/node-homey/blob/e76927e2d649201441ab16e7a87deeacdac6f0f1/lib/HomeyCompose.js#L300
But now we check
```js
if (!templateCards.templateId)
```
> fix: check correct property of templateCards

- package-lock.json
- package.json
https://github.com/SBoudrias/Inquirer.js/issues/1046
latest patch release of inquirer contains a syntax error on node 12 (usage of `??`)
> hotfix: pin inquirer version

- lib/App.js
- lib/NpmCommands.js
- package-lock.json
- package.json
Instead of rewriting file paths when tar-ing this PR copies all app files over to a `build/` directory.
We can then tar this folder for Homey Pro or mount it in the container for Homey Cloud.
This appears to perform reasonably for `com.fibaro` which I think is considered a large app. If performance becomes an issue we could try to avoid copying `node_modules`. I _think_ we can mount it separately inside the docker container and append it to the tar.
Since there where concerns about the performance of copying the files to a folder I measured and optimized the `preprocess()` step:
- `npm prune` turned out to be pretty slow, we can use `npm ls` instead which is faster but gives basically the same result.
- `ignore-walk` doesn't scale well with the number of rules, so instead of ignoring dev …
> fix: copy to build folder and use for Homey Cloud

- lib/NpmCommands.js
fixes https://github.com/athombv/homey-apps-sdk-issues/issues/234
Before NPM always used `\n` but apparently it changed in Windows 11.
> fix: NPM windows 11 newlines

- lib/App.js
Currently, developers with existing apps have an unexpected `build` folder in their Git diff and they are unsure whether it's safe to remove.
I've also renamed it to `.homeybuild` for consistency.
> rename /build to /.homeybuild, auto-add to .gitignore

- bin/cmds/app/run.js
- lib/App.js
When running a Docker container (Homey Cloud), it wasn't possible to use `npm link`-ed modules inside, because the build would fail.
The argument `homey app run --link-modules ~/Git/node-my-module` now binds `~/Git/node-my-module` to `/app/node_modules/my-module`, which makes the life of a developer _also_ developing a Node.js module much better.
> add --link-modules to homey app run

- bin/cmds/app/run.js
- lib/App.js
Allows running app during local development with host networking, which is required for UDP multicast, which some apps use for device discovery.
On non-Linux systems this requires a Docker setup that bridges the Docker VM with the host, for example Colima in combination with socket_vmnet, as documented e.g:
* https://blog.illixion.com/2023/04/colima-home-assistant/
* https://baptistout.net/posts/kubernetes-clusters-on-macos-with-loadbalancer-without-docker-desktop/
* https://github.com/lima-vm/socket_vmnet
> Add option to app run command for specifying Docker network

- package-lock.json
- package.json
This fixes the following issue that I encountered on my setup (MacOS Sonoma + Docker Desktop v4.25.0). The dockerode update seems to be a major update but there is no changelog provided. Checked the source code changes (see links below) but couldn't find anything worrying.
```
homey app run
connect ENOENT /var/run/docker.sock
✖ Error: Could not connect to Docker. Is it running?
If you haven't installed Docker yet, please download & install it first:
https://docs.docker.com/docker-for-mac/install/
at /Users/robinbolscher/development/node-homey/lib/App.js:227:13
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async App.runDocker (/Users/robinbolscher/development/node-homey/lib/App.js:210:5)
at async Object.exports.handler …
```
> fix(docker): Docker Desktop compatibility

- lib/Settings.js
I like to keep my home directory clean, therefore directories like `.athom-cli` in the home directory clutters it up, and it would be nice to set the directory with environment variables.
> feat: allow for custom homey config directory

- lib/App.js
This change allows to use of `DOCKER_HOST_GATEWAY` to specify host gateway address in scenarios where the hardcoded default bridge IP is not usable.
For example, Linux podman environments can use `host.containers.internal`.
This is based on the comment at https://github.com/athombv/node-homey/pull/371#issuecomment-1943382747.
Note that `DOCKER_HOST_GATEWAY` is not a widely used name as there seems to be no real widely used env var to refer to the gateway IP outside of `host.[docker|containers].internal` alias.
> introduce optional DOCKER_HOST_GATEWAY env var

- lib/App.js
Skips all files from the root directory when searching for files to translate.
> Skip root directory file from translate

- lib/App.js
- lib/Log.js
This ensures that the message from a JS Error is printed instead of `string.replace is not a function`.
> Fix logging when Error object is fed to log function

- bin/cmds/app/version.js
- lib/App.js
As we mainly use Gitlab it is more convenient to create the version update and tag locally by executing the version command. Adding the option to commit, tag and push the changes made by the version bump greatly helps our workflow.
The `_commitChanges` method is just a refactor from what was already used by the publish command, with an additional option which skips the "do you want to commit question" as that is already answered by supplying the command option.
> Add option to commit/tag/push changes made with version command
