athombv/node-homey

- lib/App/index.js
- lib/AppPluginRF/index.js
- lib/AppPluginZigbee/index.js
- lib/AppPluginZwave/index.js
- lib/Modules/NpmCommands.js
This will likely lead to auto-installing major (breaking) updates.
> Never install npm package @latest

- lib/App/index.js
- lib/Modules/NpmCommands.js
Check if all dependencies are present before publishing an app.
> Add npm list functionality on publish.

- .github/workflows/npm-version-bump-and-publish.yml
- package.json
TODO:
- Remove current build task
- Revoke buildserver access
Note: depends on https://github.com/athombv/node-homey/pull/21
> GitHub actions npm

- index.d.ts
Typed as any to prevent errors, unsure how to make the types correct.
> fix: add app and env types

- .github/workflows/npm-version-bump-and-publish.yml
- .github/workflows/update-homey-lib.yml
- lib/App/index.js
This homey-lib update includes validating apps compatibility w.r.t. sdk version.
> chore: update homey-lib #patch

- lib/AppPluginLog/index.js
- lib/Modules/NpmCommands.js
And not the currently available package version.
> fix: `getPackageVersion` return actually installed package version #patch

- lib/App/index.js
- lib/AppPluginCompose/index.js
fix: allow ManagerDevkit stdout websocket connection to reconnect #minor
> fix: allow ManagerDevkit stdout websocket connection to reconnect #minor

- lib/App/index.js
- package-lock.json
- package.json
This also update homey-lib which also includes a fix related to Flow card args: https://github.com/athombv/node-homey-lib/pull/239.
> fix: check Flow card args for undefined #patch

- sdk/lib/BleAdvertisement.d.ts
- sdk/manager/ble.d.ts
Relevant issue: https://github.com/athombv/homey-apps-sdk-issues/issues/146
> update BLE typings

- lib/AppPluginRF/index.js
fixes https://github.com/athombv/homey-apps-sdk-issues/issues/176
> fix: use homey-rfdriver ^3.0.0 for sdk 3

- lib/App/index.js
Making a last minute edit to a PR and not testing the code has never happened to me before, I swear!
> fix: check hasHomeyCompose before HomeyCompose build

- lib/App/index.js
[review without whitespace changes](https://github.com/athombv/node-homey/pull/140/files?diff=unified&w=1)
> chore: remove translated questions

- lib/HomeyCompose/index.js
not sure what happened here, I tested and it worked?? super confused
> hotfix: missing log import

- README.md
The readme line order got mangled somewhere.
> Fix log note position in readme

- lib/App/index.js
Noticed we check this regex a lot and the error kind of sucked.
> chore: improve invalid character check and error

- lib/App.js
- lib/ZWave.js
```
Is this an Infrared device? y/N
- Install homey-rfdriver? Y/n
Is this a 433 Mhz/868 Mhz device? y/N
- Install homey-rfdriver? Y/n
Is this a Zigbee device? y/N
- Install homey-zigbeedriver? Y/n
Is this a Z-Wave device? y/N
- Install homey-zwavedriver? Y/n
- Do you have a Z-Wave Alliance ID? Find it at ... Y/n
- - What is the Z-Wave Alliance ID?
```
Note that this is a lot of questions and the expectation is that a developer will always answer "yes" zero or one times so maybe it should be a list selection and not just a bunch of questions one after the other...
> driver create wireless questions

- lib/App.js
Create new flow --> arguments --> moved the question ```What is your placeholder?``` back, for the question ```Add another argument?``` changed the default from y to n. 
Create new flow --> tokens --> changed tokenname to tokenID, default token ID is now the same as the title (Hello World --> hello-world)
> Create flow changes

- lib/App.js
We can link to the docs after someone creates a new app
> feat: link to documentation after app create

- lib/App.js
- package-lock.json
- package.json
Changelog
- update to latest homey-lib
- ensure that `homey app flow create` and `homey app driver flow create` output valid Flow JSON
> #patch release 2.19.4

- assets/templates/app/drivers/driver.js
- bin/athom.js
- bin/cmds/app/validate.js
- bin/cmds/app/version.js
- bin/cmds/login.js
- bin/homey.js
- index.js
- lib/App.js
- lib/AthomApi.js
- lib/AthomMessage.js
- lib/GitCommands.js
- lib/HomeyCompose.js
- lib/NpmCommands.js
- lib/Settings.js
- lib/Util.js
- lib/ZWave.js
This PR fixes the linter issues that could not be fixed with an autofixer. 
I found some _really_ tricky patterns at some places. Lot's of shadowed variables, inline function definitions using a lot of local variables, and quite a number of 'for ... in' loops.
> Fix Linter issues

- bin/homey.js
- lib/GitCommands.js
feedback for https://github.com/athombv/node-homey/pull/202
> chore: feedback

- bin/homey.js
I guess I flipped these, dumb...
> fix: semver check

- lib/HomeyCompose.js
fixes bug introduced in https://github.com/athombv/node-homey/commit/73271dbb083fd6c27108f0f3cdfc087d258c9a5a
> fix: zwave parameter index replacement

- lib/App.js
When the user does not want to use TypeScript they will get the question if they want to use ESLint. If they choose 'Y', a new JSON file will be written and extra devdependencies will be installed.
> added eslint question

- lib/GitCommands.js
fixes https://app.asana.com/0/1164420446126602/1200731234877762/f
> fix: don't log git error to console

- .eslintrc.json
- bin/cmds/app/validate.js
- lib/App.js
- package-lock.json
- package.json
Changelog
- `homey app create` now adds an ESLint config by default
- Fixed a bug that caused zwaveParameterIndex to never get replaces
- Removed logging of GIT command errors
> release v2.21.0 #minor: create eslint config

- bin/cmds/app/manage.js
- bin/cmds/docs.js
- bin/cmds/tools.js
- config.js
now the url commands are: 
```
homey docs
homey tools
homey app view
homey app manage
```
> feat: `homey app manage` to open devtools app page

- package.json
To prevent users hitting Marak his update that adds an infinite loop to the colors package.
> Constraint colors dependency

- lib/AthomApi.js
- Validation improvements
- Validation error message improvements
- Add tests
- Add warning when using permission `speech-input`
> chore: update homey-lib #minor

- lib/App.js
This fixes an issue with (linked) dev dependencies being validated.
> fix: validate .homeybuild folder

- lib/App.js
- package-lock.json
- package.json
- Fixes running apps on Windows Subsystem for Linux.
- Fixes validation issue caused by symlinking dev dependencies.
> Merge Master into Production (v2.33.5)

- assets/templates/app/drivers/device.ts
Fixes https://github.com/athombv/homey-apps-sdk-issues/issues/261
> fix: `Device.onSettings` types

- lib/App.js
- package-lock.json
- package.json
- Fixes types of `Device.onSettings` parameters in TypeScript template
> Merge Master into Production (v2.33.6)

- package-lock.json
- package.json
This includes Zigbee driver manifest validation.
> chore: update homey-lib@2.22.0
